[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
contract = "FSCrRyV4Ed1JsuPEA88BBHHob6i9FGktVynL2mfLjx38"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
